repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
        files: ^pyzx_daemon/
      - id: ruff-format
        files: ^pyzx_daemon/
